import type { Metadata } from "next";
import StyledComponentsRegistry from "@/app/lib/registry";
import {StyledWrapper} from "@/app/style";
import Header from "@/app/blocks/header/header";

export const metadata: Metadata = {
  title: "Personal Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, auth
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode;
}>) {
  return (
          <html lang="en">
              <StyledComponentsRegistry>
                    <body id={'root'}>
                        <StyledWrapper>
                            <Header />
                            <main>
                                {children}
                                {auth}
                            </main>
                        </StyledWrapper>
                    </body>
              </StyledComponentsRegistry>
          </html>
  );
}
